# Generated by Django 5.0.6 on 2024-05-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
