# Generated by Django 5.0.6 on 2024-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_fanlogdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanlogdetails',
            name='change',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
